version: "3.9"

services:
  db:
    image: mysql:8.0
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci"
    ]
    container_name: bogtoworld_db
    environment:
      MYSQL_DATABASE: bogtoworld
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: bogtoworld_backend
    environment:
      PORT: 4000
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: bogtoworld
      JWT_SECRET: supersecret_dev
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
      # Si quieres hornear VITE_API_URL en build:
      # args:
      #   - VITE_API_URL=/api
    container_name: bogtoworld_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  dbdata:
